/** 
@file VT_Vaults.hpp

@brief Vaulted Thermals: Vault Definitions

@details

Vaults (Designator):
MagmaChamber
V0
V1
V2
V3
V4


Important: Higher numbered vaults may require a lower level vault to be opened. 
If the vault is not open, it will define the open definition itself implicitly.

Opening the MagmaChamber vault is unique in that it affects all other vaults.
When opened, the definition will change the loader interfaced with for all the implementation
in the other vaults to the loader generated by the MagmaChamber vault.
Define macro: VT_Vault_MagmaChamber_Open if you want this. [Note: Currently not implemented
*/





#pragma once



#ifndef VT_Option__Use_Long_Namespace
/**
@namespace VaultedThermals

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper)

@details For long namespace: #define VT_Option__Use_Long_Namespace
*/
namespace VT
#else
/**
@namespace VaultedThermals

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper)

@details VT_Option__Use_Long_Namespace in use.
*/
namespace VaultedThermals
#endif
{
	/** @namespace Corridors
 
	@brief Contains shared definitions between the vaults.
	*/
	namespace Corridors {}

	/** @namespace Vault_MagmaChamber

	@todo Look into possibly implementing with the Volk library.

	@brief Meta-Loading Setup.

	@details When the heat at the control gate isn't enough. 
	*/
	namespace Vault_MagmaChamber {}

	/** @namespace Vault_0

	@brief Backend vault for VaultedThermals

	@details For now only abstracts away OS Platform details and basic meta-structure definitions.
	*/
	namespace V0 { using namespace Corridors; }

	/** @namespace Vault_1

	@brief 1:1 Wrapping of Vulkan API
	*/
	namespace V1 { using namespace Corridors; }

	/** @namespace Vault_2

	@brief Repetitive functionality wrapping.
	*/
	namespace V2 { using namespace Corridors; }

	/** @namespace Vault_3

	@brief Object-Oriented wrapping
	*/
	namespace V3 { using namespace Corridors; }

	/** @namespace Vault_4

	@brief Object-Oriented bootstrapped backend
	*/
	namespace V4 { using namespace Corridors; }
}
