var searchData=
[
  ['vaultedthermals',['VaultedThermals',['../index.html',1,'']]],
  ['validation',['Validation',['../structVT_1_1V1_1_1AppInstance_1_1Validation.html',1,'VT::V1::AppInstance']]],
  ['validation',['Validation',['../structVT_1_1V2_1_1AppInstance_1_1Validation.html',1,'VT::V2::AppInstance']]],
  ['vault_5f0',['Vault_0',['../namespaceVault__0.html',1,'Vault_0'],['../group__Vault__0.html',1,'(Global Namespace)']]],
  ['vault_5f1',['Vault_1',['../namespaceVault__1.html',1,'Vault_1'],['../group__Vault__1.html',1,'(Global Namespace)']]],
  ['vault_5f2',['Vault_2',['../namespaceVault__2.html',1,'Vault_2'],['../group__Vault__2.html',1,'(Global Namespace)']]],
  ['vault_5f3',['Vault_3',['../namespaceVault__3.html',1,'Vault_3'],['../group__Vault__3.html',1,'(Global Namespace)']]],
  ['vault_5f4',['Vault_4',['../namespaceVault__4.html',1,'Vault_4'],['../group__Vault__4.html',1,'(Global Namespace)']]],
  ['vault_5fmagmachamber',['Vault_MagmaChamber',['../namespaceVault__MagmaChamber.html',1,'Vault_MagmaChamber'],['../group__Vault__MagmaChamber.html',1,'(Global Namespace)']]],
  ['vaultedthermals',['VaultedThermals',['../namespaceVaultedThermals.html',1,'VaultedThermals'],['../group__VaultedThermals.html',1,'(Global Namespace)']]],
  ['vaultedthermals_2ehpp',['VaultedThermals.hpp',['../VaultedThermals_8hpp.html',1,'']]],
  ['vertexinputstate',['VertexInputState',['../structVT_1_1V2_1_1Pipeline_1_1VertexInputState.html',1,'VT::V2::Pipeline']]],
  ['vertexinputstate',['VertexInputState',['../structVT_1_1V1_1_1Pipeline_1_1VertexInputState.html',1,'VT::V1::Pipeline']]],
  ['viewport',['Viewport',['../structVT_1_1Corridors_1_1Viewport.html',1,'VT::Corridors']]],
  ['viewportstate',['ViewportState',['../structVT_1_1V1_1_1Pipeline_1_1ViewportState.html',1,'VT::V1::Pipeline']]],
  ['viewportstate',['ViewportState',['../structVT_1_1V2_1_1Pipeline_1_1ViewportState.html',1,'VT::V2::Pipeline']]],
  ['vk_5ffptr',['VK_FPtr',['../group__Pointers.html#gab996b6374e8bc815760f6c2f84dad92c',1,'VT::Corridors']]],
  ['vkapi_5fadditional_5fcapabilities',['VKAPI_Additional_Capabilities',['../group__VKAPI__Additional__Capabilities.html',1,'']]],
  ['vkapi_5fclear_5fcommands',['VKAPI_Clear_Commands',['../group__VKAPI__Clear__Commands.html',1,'']]],
  ['vkapi_5fcommand_5fbuffers',['VKAPI_Command_Buffers',['../group__VKAPI__Command__Buffers.html',1,'']]],
  ['vkapi_5fcopy_5fcommands',['VKAPI_Copy_Commands',['../group__VKAPI__Copy__Commands.html',1,'']]],
  ['vkapi_5fdebugging',['VKAPI_Debugging',['../group__VKAPI__Debugging.html',1,'']]],
  ['vkapi_5fdeferred_5fhost_5foperations',['VKAPI_Deferred_Host_Operations',['../group__VKAPI__Deferred__Host__Operations.html',1,'']]],
  ['vkapi_5fdevice_2dgenerated_5fcommands',['VKAPI_Device-Generated_Commands',['../group__VKAPI__Device-Generated__Commands.html',1,'']]],
  ['vkapi_5fdevices_5fand_5fqueues',['VKAPI_Devices_and_Queues',['../group__VKAPI__Devices__and__Queues.html',1,'']]],
  ['vkapi_5fdispatching_5fcommands',['VKAPI_Dispatching_Commands',['../group__VKAPI__Dispatching__Commands.html',1,'']]],
  ['vkapi_5fdrawing_5fcommands',['VKAPI_Drawing_Commands',['../group__VKAPI__Drawing__Commands.html',1,'']]],
  ['vkapi_5fextending_5fvulkan',['VKAPI_Extending_Vulkan',['../group__VKAPI__Extending__Vulkan.html',1,'']]],
  ['vkapi_5ffeatures',['VKAPI_Features',['../group__VKAPI__Features.html',1,'']]],
  ['vkapi_5ffixed_2dfunction_5fvertex_5fpost_2dprocessing',['VKAPI_Fixed-Function_Vertex_Post-Processing',['../group__VKAPI__Fixed-Function__Vertex__Post-Processing.html',1,'']]],
  ['vkapi_5ffixed_2dfunction_5fvertex_5fprocessing',['VKAPI_Fixed-Function_Vertex_Processing',['../group__VKAPI__Fixed-Function__Vertex__Processing.html',1,'']]],
  ['vkapi_5fformats',['VKAPI_Formats',['../group__VKAPI__Formats.html',1,'']]],
  ['vkapi_5ffragment_5fdensity_5fmap_5foperations',['VKAPI_Fragment_Density_Map_Operations',['../group__VKAPI__Fragment__Density__Map__Operations.html',1,'']]],
  ['vkapi_5ffragment_5foperations',['VKAPI_Fragment_Operations',['../group__VKAPI__Fragment__Operations.html',1,'']]],
  ['vkapi_5ffundamentals',['VKAPI_Fundamentals',['../group__VKAPI__Fundamentals.html',1,'']]],
  ['vkapi_5fgeometry_5fshading',['VKAPI_Geometry_Shading',['../group__VKAPI__Geometry__Shading.html',1,'']]],
  ['vkapi_5fimage_5foperations',['VKAPI_Image_Operations',['../group__VKAPI__Image__Operations.html',1,'']]],
  ['vkapi_5finitialization',['VKAPI_Initialization',['../group__VKAPI__Initialization.html',1,'']]],
  ['vkapi_5fintroduction',['VKAPI_Introduction',['../group__VKAPI__Introduction.html',1,'']]],
  ['vkapi_5flimits',['VKAPI_Limits',['../group__VKAPI__Limits.html',1,'']]],
  ['vkapi_5fmemory_5fallocation',['VKAPI_Memory_Allocation',['../group__VKAPI__Memory__Allocation.html',1,'']]],
  ['vkapi_5fmesh_5fshading',['VKAPI_Mesh_Shading',['../group__VKAPI__Mesh__Shading.html',1,'']]],
  ['vkapi_5fpipelines',['VKAPI_Pipelines',['../group__VKAPI__Pipelines.html',1,'']]],
  ['vkapi_5fprivate_5fdata',['VKAPI_Private_Data',['../group__VKAPI__Private__Data.html',1,'']]],
  ['vkapi_5fqueries',['VKAPI_Queries',['../group__VKAPI__Queries.html',1,'']]],
  ['vkapi_5frasterization',['VKAPI_Rasterization',['../group__VKAPI__Rasterization.html',1,'']]],
  ['vkapi_5fray_5ftracing',['VKAPI_Ray_Tracing',['../group__VKAPI__Ray__Tracing.html',1,'']]],
  ['vkapi_5fray_5ftraversal',['VKAPI_Ray_Traversal',['../group__VKAPI__Ray__Traversal.html',1,'']]],
  ['vkapi_5frender_5fpass',['VKAPI_Render_Pass',['../group__VKAPI__Render__Pass.html',1,'']]],
  ['vkapi_5fresource_5fcreation',['VKAPI_Resource_Creation',['../group__VKAPI__Resource__Creation.html',1,'']]],
  ['vkapi_5fresource_5fdescriptors',['VKAPI_Resource_Descriptors',['../group__VKAPI__Resource__Descriptors.html',1,'']]],
  ['vkapi_5fsamplers',['VKAPI_Samplers',['../group__VKAPI__Samplers.html',1,'']]],
  ['vkapi_5fshader_5finterfaces',['VKAPI_Shader_Interfaces',['../group__VKAPI__Shader__Interfaces.html',1,'']]],
  ['vkapi_5fshaders',['VKAPI_Shaders',['../group__VKAPI__Shaders.html',1,'']]],
  ['vkapi_5fsparse_5fresources',['VKAPI_Sparse_Resources',['../group__VKAPI__Sparse__Resources.html',1,'']]],
  ['vkapi_5fsynchronization_5fand_5fcache_5fcontrol',['VKAPI_Synchronization_and_Cache_Control',['../group__VKAPI__Synchronization__and__Cache__Control.html',1,'']]],
  ['vkapi_5ftessellation',['VKAPI_Tessellation',['../group__VKAPI__Tessellation.html',1,'']]],
  ['vkapi_5fthe_5fframebuffer',['VKAPI_The_Framebuffer',['../group__VKAPI__The__Framebuffer.html',1,'']]],
  ['vkapi_5fwindow_5fsystem_5fintegration_5fwsi',['VKAPI_Window_System_Integration_WSI',['../group__VKAPI__Window__System__Integration__WSI.html',1,'']]],
  ['vkstruct_5fbase',['VKStruct_Base',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkallocationcallbacks_20_3e',['VKStruct_Base&lt; VkAllocationCallbacks &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkattachmentdescription_20_3e',['VKStruct_Base&lt; VkAttachmentDescription &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkattachmentreference_20_3e',['VKStruct_Base&lt; VkAttachmentReference &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbaseinstructure_20_3e',['VKStruct_Base&lt; VkBaseInStructure &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbaseoutstructure_20_3e',['VKStruct_Base&lt; VkBaseOutStructure &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbuffercopy_20_3e',['VKStruct_Base&lt; VkBufferCopy &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbuffercreateinfo_2c_20estructuretype_3a_3abuffer_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkBufferCreateInfo, EStructureType::Buffer_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbufferimagecopy_20_3e',['VKStruct_Base&lt; VkBufferImageCopy &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbuffermemorybarrier_2c_20estructuretype_3a_3abuffermemory_5fbarrier_20_3e',['VKStruct_Base&lt; VkBufferMemoryBarrier, EStructureType::BufferMemory_Barrier &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkbufferviewcreateinfo_2c_20estructuretype_3a_3abufferview_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkBufferViewCreateInfo, EStructureType::BufferView_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandbufferallocateinfo_2c_20estructuretype_3a_3acommandbuffer_5fallocateinfo_20_3e',['VKStruct_Base&lt; VkCommandBufferAllocateInfo, EStructureType::CommandBuffer_AllocateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandbufferbegininfo_2c_20estructuretype_3a_3acommandbuffer_5fbegininfo_20_3e',['VKStruct_Base&lt; VkCommandBufferBeginInfo, EStructureType::CommandBuffer_BeginInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandbufferinheritanceconditionalrenderinginfoext_2c_20estructuretype_3a_3acommandbuffer_5finheritance_5fconditionalrendering_5finfo_5fext_20_3e',['VKStruct_Base&lt; VkCommandBufferInheritanceConditionalRenderingInfoEXT, EStructureType::CommandBuffer_Inheritance_ConditionalRendering_Info_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandbufferinheritanceinfo_2c_20estructuretype_3a_3acommandbuffer_5finheritanceinfo_20_3e',['VKStruct_Base&lt; VkCommandBufferInheritanceInfo, EStructureType::CommandBuffer_InheritanceInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandbufferinheritancerenderpasstransforminfoqcom_2c_20estructuretype_3a_3acommandbufferinheritance_5frenderpasstransform_5finfo_5fqcom_20_3e',['VKStruct_Base&lt; VkCommandBufferInheritanceRenderPassTransformInfoQCOM, EStructureType::CommandBufferInheritance_RenderPassTransform_Info_QCOM &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcommandpoolcreateinfo_2c_20estructuretype_3a_3acommandpool_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkCommandPoolCreateInfo, EStructureType::CommandPool_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcomponentmapping_20_3e',['VKStruct_Base&lt; VkComponentMapping &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcomputepipelinecreateinfo_2c_20estructuretype_3a_3acomputepipeline_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkComputePipelineCreateInfo, EStructureType::ComputePipeline_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkconformanceversion_20_3e',['VKStruct_Base&lt; VkConformanceVersion &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkcopydescriptorset_20_3e',['VKStruct_Base&lt; VkCopyDescriptorSet &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkd3d12fencesubmitinfokhr_20_3e',['VKStruct_Base&lt; VkD3D12FenceSubmitInfoKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdebugutilslabelext_2c_20estructuretype_3a_3adebugutils_5flabel_5fext_20_3e',['VKStruct_Base&lt; VkDebugUtilsLabelEXT, EStructureType::DebugUtils_Label_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdebugutilsmessengercallbackdataext_2c_20estructuretype_3a_3adebugutils_5fmessengercallback_5fdata_5fext_20_3e',['VKStruct_Base&lt; VkDebugUtilsMessengerCallbackDataEXT, EStructureType::DebugUtils_MessengerCallback_Data_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdebugutilsmessengercreateinfoext_2c_20estructuretype_3a_3adebugutils_5fmessenger_5fcreateinfo_5fext_20_3e',['VKStruct_Base&lt; VkDebugUtilsMessengerCreateInfoEXT, EStructureType::DebugUtils_Messenger_CreateInfo_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdebugutilsobjectnameinfoext_2c_20estructuretype_3a_3adebugutils_5fobjectname_5finfo_5fext_20_3e',['VKStruct_Base&lt; VkDebugUtilsObjectNameInfoEXT, EStructureType::DebugUtils_ObjectName_Info_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorbufferinfo_20_3e',['VKStruct_Base&lt; VkDescriptorBufferInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorimageinfo_20_3e',['VKStruct_Base&lt; VkDescriptorImageInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorpoolcreateinfo_2c_20estructuretype_3a_3adescriptor_5fpool_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDescriptorPoolCreateInfo, EStructureType::Descriptor_Pool_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorpoolsize_20_3e',['VKStruct_Base&lt; VkDescriptorPoolSize &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetallocateinfo_2c_20estructuretype_3a_3adescriptor_5fsetallocateinfo_20_3e',['VKStruct_Base&lt; VkDescriptorSetAllocateInfo, EStructureType::Descriptor_SetAllocateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetlayoutbinding_20_3e',['VKStruct_Base&lt; VkDescriptorSetLayoutBinding &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetlayoutbindingflagscreateinfo_2c_20estructuretype_3a_3adescriptor_5fsetlayoutbindingflags_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDescriptorSetLayoutBindingFlagsCreateInfo, EStructureType::Descriptor_SetLayoutBindingFlags_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetlayoutcreateinfo_2c_20estructuretype_3a_3adescriptor_5fsetlayout_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDescriptorSetLayoutCreateInfo, EStructureType::Descriptor_SetLayout_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetlayoutsupport_2c_20estructuretype_3a_3adescriptor_5fsetlayoutsupport_20_3e',['VKStruct_Base&lt; VkDescriptorSetLayoutSupport, EStructureType::Descriptor_SetLayoutSupport &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdescriptorsetvariabledescriptorcountlayoutsupport_2c_20estructuretype_3a_3adescriptor_5fsetvariable_5fdescriptor_5fcountlayoutsupport_20_3e',['VKStruct_Base&lt; VkDescriptorSetVariableDescriptorCountLayoutSupport, EStructureType::Descriptor_SetVariable_Descriptor_CountLayoutSupport &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicecreateinfo_2c_20estructuretype_3a_3adevice_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDeviceCreateInfo, EStructureType::Device_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicediagnosticsconfigcreateinfonv_2c_20estructuretype_3a_3adevicediagnosticsconfig_5fcreateinfo_5fnv_20_3e',['VKStruct_Base&lt; VkDeviceDiagnosticsConfigCreateInfoNV, EStructureType::DeviceDiagnosticsConfig_CreateInfo_NV &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdeviceeventinfoext_2c_20estructuretype_3a_3adevice_5feventinfo_5fext_20_3e',['VKStruct_Base&lt; VkDeviceEventInfoEXT, EStructureType::Device_EventInfo_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicegroupcommandbufferbegininfo_20_3e',['VKStruct_Base&lt; VkDeviceGroupCommandBufferBeginInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicegroupdevicecreateinfo_2c_20estructuretype_3a_3adevice_5fgroupdevice_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDeviceGroupDeviceCreateInfo, EStructureType::Device_GroupDevice_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicegroupsubmitinfo_20_3e',['VKStruct_Base&lt; VkDeviceGroupSubmitInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicememoryoverallocationcreateinfoamd_2c_20estructuretype_3a_3adevicememory_5foverallocation_5fcreateinfo_5famd_20_3e',['VKStruct_Base&lt; VkDeviceMemoryOverallocationCreateInfoAMD, EStructureType::DeviceMemory_Overallocation_CreateInfo_AMD &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdeviceprivatedatacreateinfoext_2c_20estructuretype_3a_3adevice_5fprivatedata_5fcreateinfo_5fext_20_3e',['VKStruct_Base&lt; VkDevicePrivateDataCreateInfoEXT, EStructureType::Device_PrivateData_CreateInfo_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicequeuecreateinfo_2c_20estructuretype_3a_3adevicequeue_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkDeviceQueueCreateInfo, EStructureType::DeviceQueue_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdevicequeueinfo2_2c_20estructuretype_3a_3adevicequeueinfo2_20_3e',['VKStruct_Base&lt; VkDeviceQueueInfo2, EStructureType::DeviceQueueInfo2 &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkdisplayeventinfoext_2c_20estructuretype_3a_3adisplay_5feventinfo_5fext_20_3e',['VKStruct_Base&lt; VkDisplayEventInfoEXT, EStructureType::Display_EventInfo_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkeventcreateinfo_2c_20estructuretype_3a_3aevent_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkEventCreateInfo, EStructureType::Event_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkexportfencecreateinfo_2c_20estructuretype_3a_3aexportfence_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkExportFenceCreateInfo, EStructureType::ExportFence_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkexportfencewin32handleinfokhr_2c_20estructuretype_3a_3aexportfence_5fwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkExportFenceWin32HandleInfoKHR, EStructureType::ExportFence_Win32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkexportsemaphorecreateinfo_2c_20estructuretype_3a_3aexport_5fsemaphore_5fcreateinfo_5fkhr_20_3e',['VKStruct_Base&lt; VkExportSemaphoreCreateInfo, EStructureType::Export_Semaphore_CreateInfo_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkexportsemaphorewin32handleinfokhr_2c_20estructuretype_3a_3aexportsemaphore_5fwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkExportSemaphoreWin32HandleInfoKHR, EStructureType::ExportSemaphore_Win32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkextensionproperties_20_3e',['VKStruct_Base&lt; VkExtensionProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkextent2d_20_3e',['VKStruct_Base&lt; VkExtent2D &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkextent3d_20_3e',['VKStruct_Base&lt; VkExtent3D &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkfencecreateinfo_2c_20estructuretype_3a_3afence_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkFenceCreateInfo, EStructureType::Fence_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkfencegetfdinfokhr_2c_20estructuretype_3a_3afence_5fget_5ffd_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkFenceGetFdInfoKHR, EStructureType::Fence_Get_FD_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkfencegetwin32handleinfokhr_2c_20estructuretype_3a_3afence_5fgetwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkFenceGetWin32HandleInfoKHR, EStructureType::Fence_GetWin32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkformatproperties_20_3e',['VKStruct_Base&lt; VkFormatProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkframebuffercreateinfo_2c_20estructuretype_3a_3aframebuffer_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkFramebufferCreateInfo, EStructureType::Framebuffer_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkgraphicspipelinecreateinfo_2c_20estructuretype_3a_3agraphicspipeline_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkGraphicsPipelineCreateInfo, EStructureType::GraphicsPipeline_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkgraphicspipelineshadergroupscreateinfonv_2c_20estructuretype_3a_3agraphicspipeline_5fshadergroups_5fcreateinfo_5fnv_20_3e',['VKStruct_Base&lt; VkGraphicsPipelineShaderGroupsCreateInfoNV, EStructureType::GraphicsPipeline_ShaderGroups_CreateInfo_NV &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkgraphicsshadergroupcreateinfonv_2c_20estructuretype_3a_3agraphicsshadergroup_5fcreateinfo_5fnv_20_3e',['VKStruct_Base&lt; VkGraphicsShaderGroupCreateInfoNV, EStructureType::GraphicsShaderGroup_CreateInfo_NV &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimageblit_20_3e',['VKStruct_Base&lt; VkImageBlit &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimagecreateinfo_2c_20estructuretype_3a_3aimage_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkImageCreateInfo, EStructureType::Image_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimagememorybarrier_2c_20estructuretype_3a_3aimagememory_5fbarrier_20_3e',['VKStruct_Base&lt; VkImageMemoryBarrier, EStructureType::ImageMemory_Barrier &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimagesubresourcelayers_20_3e',['VKStruct_Base&lt; VkImageSubresourceLayers &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimagesubresourcerange_20_3e',['VKStruct_Base&lt; VkImageSubresourceRange &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimageviewcreateinfo_2c_20estructuretype_3a_3aimageview_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkImageViewCreateInfo, EStructureType::ImageView_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimportfencefdinfokhr_2c_20estructuretype_3a_3aimportfence_5ffd_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkImportFenceFdInfoKHR, EStructureType::ImportFence_FD_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimportfencewin32handleinfokhr_2c_20estructuretype_3a_3aimportfence_5fwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkImportFenceWin32HandleInfoKHR, EStructureType::ImportFence_Win32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimportsemaphorefdinfokhr_2c_20estructuretype_3a_3aimportsemaphore_5ffd_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkImportSemaphoreFdInfoKHR, EStructureType::ImportSemaphore_FD_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkimportsemaphorewin32handleinfokhr_2c_20estructuretype_3a_3aimportsemaphore_5fwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkImportSemaphoreWin32HandleInfoKHR, EStructureType::ImportSemaphore_Win32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkinstancecreateinfo_2c_20estructuretype_3a_3aapplicationinformation_20_3e',['VKStruct_Base&lt; VkInstanceCreateInfo, EStructureType::ApplicationInformation &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkinstancecreateinfo_2c_20estructuretype_3a_3ainstance_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkInstanceCreateInfo, EStructureType::Instance_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vklayerproperties_20_3e',['VKStruct_Base&lt; VkLayerProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkmemoryallocateinfo_2c_20estructuretype_3a_3amemoryallocateinfo_20_3e',['VKStruct_Base&lt; VkMemoryAllocateInfo, EStructureType::MemoryAllocateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkmemorybarrier_2c_20estructuretype_3a_3amemory_5fbarrier_20_3e',['VKStruct_Base&lt; VkMemoryBarrier, EStructureType::Memory_Barrier &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkmemoryheap_20_3e',['VKStruct_Base&lt; VkMemoryHeap &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkmemoryrequirements_20_3e',['VKStruct_Base&lt; VkMemoryRequirements &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkmemorytype_20_3e',['VKStruct_Base&lt; VkMemoryType &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkoffset2d_20_3e',['VKStruct_Base&lt; VkOffset2D &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkoffset3d_20_3e',['VKStruct_Base&lt; VkOffset3D &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkperformancecounterdescriptionkhr_20_3e',['VKStruct_Base&lt; VkPerformanceCounterDescriptionKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkperformancecounterkhr_2c_20estructuretype_3a_3aperformacnecounter_5fkhr_20_3e',['VKStruct_Base&lt; VkPerformanceCounterKHR, EStructureType::PerformacneCounter_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkperformancequerysubmitinfokhr_20_3e',['VKStruct_Base&lt; VkPerformanceQuerySubmitInfoKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicefeatures_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceFeatures &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicegroupproperties_2c_20estructuretype_3a_3aphysicaldevice_5fgroupproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceGroupProperties, EStructureType::PhysicalDevice_GroupProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldeviceidproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceIDProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicelimits_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceLimits &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicememoryproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceMemoryProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicepcibusinfopropertiesext_2c_20estructuretype_3a_3aphysicaldevice_5fpci_5fbus_5finfo_5fproperties_5fext_20_3e',['VKStruct_Base&lt; VkPhysicalDevicePCIBusInfoPropertiesEXT, EStructureType::PhysicalDevice_PCI_BUS_Info_Properties_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldeviceproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldeviceproperties2_2c_20estructuretype_3a_3aphysicaldevice_5fproperties_5f2_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceProperties2, EStructureType::PhysicalDevice_Properties_2 &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicesparseproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceSparseProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicevulkan11properties_2c_20estructuretype_3a_3aphysicaldevice_5fvulkan_5f1_5f1_5fproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceVulkan11Properties, EStructureType::PhysicalDevice_Vulkan_1_1_Properties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkphysicaldevicevulkan12properties_2c_20estructuretype_3a_3aphysicaldevice_5fvulkan_5f1_5f2_5fproperties_20_3e',['VKStruct_Base&lt; VkPhysicalDeviceVulkan12Properties, EStructureType::PhysicalDevice_Vulkan_1_2_Properties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinecachecreateinfo_2c_20estructuretype_3a_3apipeline_5fcache_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineCacheCreateInfo, EStructureType::Pipeline_Cache_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinecolorblendattachmentstate_2c_20estructuretype_3a_3apipeline_5fcolorblendadvancedstate_5fcreateinfo_5fext_20_3e',['VKStruct_Base&lt; VkPipelineColorBlendAttachmentState, EStructureType::Pipeline_ColorBlendAdvancedState_CreateInfo_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinecolorblendstatecreateinfo_2c_20estructuretype_3a_3apipeline_5fcolorblendstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineColorBlendStateCreateInfo, EStructureType::Pipeline_ColorBlendState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinedepthstencilstatecreateinfo_2c_20estructuretype_3a_3apipeline_5fdepthstencilstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineDepthStencilStateCreateInfo, EStructureType::Pipeline_DepthStencilState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinedynamicstatecreateinfo_2c_20estructuretype_3a_3apipeline_5fdynamicstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineDynamicStateCreateInfo, EStructureType::Pipeline_DynamicState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelineinputassemblystatecreateinfo_2c_20estructuretype_3a_3apipeline_5finputassemblystate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineInputAssemblyStateCreateInfo, EStructureType::Pipeline_InputAssemblyState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinelayoutcreateinfo_2c_20estructuretype_3a_3apipeline_5flayout_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineLayoutCreateInfo, EStructureType::Pipeline_Layout_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinemultisamplestatecreateinfo_2c_20estructuretype_3a_3apipeline_5fmultisamplestate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineMultisampleStateCreateInfo, EStructureType::Pipeline_MultisampleState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinerasterizationstatecreateinfo_2c_20estructuretype_3a_3apipeline_5frasterizationstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineRasterizationStateCreateInfo, EStructureType::Pipeline_RasterizationState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelineshaderstagecreateinfo_2c_20estructuretype_3a_3apipeline_5fshaderstage_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineShaderStageCreateInfo, EStructureType::Pipeline_ShaderStage_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinetessellationstatecreateinfo_2c_20estructuretype_3a_3apipeline_5ftessellationstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineTessellationStateCreateInfo, EStructureType::Pipeline_TessellationState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelinevertexinputstatecreateinfo_2c_20estructuretype_3a_3apipeline_5fvertexinputstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineVertexInputStateCreateInfo, EStructureType::Pipeline_VertexInputState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpipelineviewportstatecreateinfo_2c_20estructuretype_3a_3apipeline_5fviewportstate_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkPipelineViewportStateCreateInfo, EStructureType::Pipeline_ViewportState_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpresentinfokhr_2c_20estructuretype_3a_3apresentinfo_5fkhr_20_3e',['VKStruct_Base&lt; VkPresentInfoKHR, EStructureType::PresentInfo_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkprotectedsubmitinfo_20_3e',['VKStruct_Base&lt; VkProtectedSubmitInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkpushconstantrange_20_3e',['VKStruct_Base&lt; VkPushConstantRange &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkqueuefamilycheckpointpropertiesnv_2c_20estructuretype_3a_3aqueuefamilycheckpoint_5fproperties_5fnv_20_3e',['VKStruct_Base&lt; VkQueueFamilyCheckpointPropertiesNV, EStructureType::QueueFamilyCheckpoint_Properties_NV &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkqueuefamilyproperties_20_3e',['VKStruct_Base&lt; VkQueueFamilyProperties &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkqueuefamilyproperties2_2c_20estructuretype_3a_3aqueuefamily_5fproperties_5f2_20_3e',['VKStruct_Base&lt; VkQueueFamilyProperties2, EStructureType::QueueFamily_Properties_2 &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkrect2d_20_3e',['VKStruct_Base&lt; VkRect2D &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkrenderpassbegininfo_2c_20estructuretype_3a_3arenderpass_5fbegininfo_20_3e',['VKStruct_Base&lt; VkRenderPassBeginInfo, EStructureType::RenderPass_BeginInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkrenderpasscreateinfo_2c_20estructuretype_3a_3arenderpass_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkRenderPassCreateInfo, EStructureType::RenderPass_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksamplercreateinfo_2c_20estructuretype_3a_3asampler_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkSamplerCreateInfo, EStructureType::Sampler_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphorecreateinfo_2c_20estructuretype_3a_3asemaphore_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkSemaphoreCreateInfo, EStructureType::Semaphore_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphoregetfdinfokhr_2c_20estructuretype_3a_3asemaphore_5fget_5ffd_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkSemaphoreGetFdInfoKHR, EStructureType::Semaphore_Get_FD_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphoregetwin32handleinfokhr_2c_20estructuretype_3a_3asemaphore_5fgetwin32handle_5finfo_5fkhr_20_3e',['VKStruct_Base&lt; VkSemaphoreGetWin32HandleInfoKHR, EStructureType::Semaphore_GetWin32Handle_Info_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphoresignalinfo_2c_20estructuretype_3a_3asemaphore_5fsignalinfo_20_3e',['VKStruct_Base&lt; VkSemaphoreSignalInfo, EStructureType::Semaphore_SignalInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphoretypecreateinfo_2c_20estructuretype_3a_3asemaphoretype_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkSemaphoreTypeCreateInfo, EStructureType::SemaphoreType_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksemaphorewaitinfo_2c_20estructuretype_3a_3asemaphore_5fwaitinfo_20_3e',['VKStruct_Base&lt; VkSemaphoreWaitInfo, EStructureType::Semaphore_WaitInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkshadermodulecreateinfo_2c_20estructuretype_3a_3ashadermodule_5fcreateinfo_20_3e',['VKStruct_Base&lt; VkShaderModuleCreateInfo, EStructureType::ShaderModule_CreateInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkspecializationinfo_20_3e',['VKStruct_Base&lt; VkSpecializationInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkspecializationmapentry_20_3e',['VKStruct_Base&lt; VkSpecializationMapEntry &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkstencilopstate_20_3e',['VKStruct_Base&lt; VkStencilOpState &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksubmitinfo_2c_20estructuretype_3a_3asubmitinfo_20_3e',['VKStruct_Base&lt; VkSubmitInfo, EStructureType::SubmitInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksubpassdependency_20_3e',['VKStruct_Base&lt; VkSubpassDependency &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksubpassdescription_20_3e',['VKStruct_Base&lt; VkSubpassDescription &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksurfacecapabilitieskhr_20_3e',['VKStruct_Base&lt; VkSurfaceCapabilitiesKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vksurfaceformatkhr_20_3e',['VKStruct_Base&lt; VkSurfaceFormatKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkswapchaincreateinfokhr_2c_20estructuretype_3a_3aswapchain_5fcreateinfo_5fkhr_20_3e',['VKStruct_Base&lt; VkSwapchainCreateInfoKHR, EStructureType::SwapChain_CreateInfo_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vktimelinesemaphoresubmitinfo_20_3e',['VKStruct_Base&lt; VkTimelineSemaphoreSubmitInfo &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkvalidationfeaturesext_2c_20estructuretype_3a_3avalidationfeatures_5fext_20_3e',['VKStruct_Base&lt; VkValidationFeaturesEXT, EStructureType::ValidationFeatures_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkvalidationflagsext_2c_20estructuretype_3a_3avalidationflags_5fext_20_3e',['VKStruct_Base&lt; VkValidationFlagsEXT, EStructureType::ValidationFlags_EXT &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkvertexinputattributedescription_20_3e',['VKStruct_Base&lt; VkVertexInputAttributeDescription &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkvertexinputbindingdescription_20_3e',['VKStruct_Base&lt; VkVertexInputBindingDescription &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkviewport_20_3e',['VKStruct_Base&lt; VkViewport &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkwin32keyedmutexacquirereleaseinfokhr_20_3e',['VKStruct_Base&lt; VkWin32KeyedMutexAcquireReleaseInfoKHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkwin32surfacecreateinfokhr_2c_20estructuretype_3a_3awin32_5fsurface_5fcreateinfo_5fkhr_20_3e',['VKStruct_Base&lt; VkWin32SurfaceCreateInfoKHR, EStructureType::Win32_Surface_CreateInfo_KHR &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vkstruct_5fbase_3c_20vkwritedescriptorset_2c_20estructuretype_3a_3awritedescriptor_5fset_20_3e',['VKStruct_Base&lt; VkWriteDescriptorSet, EStructureType::WriteDescriptor_Set &gt;',['../structVT_1_1V0_1_1VKStruct__Base.html',1,'VT::V0']]],
  ['vktype',['VkType',['../structVT_1_1V0_1_1VKStruct__Base.html#a77740b08233072585c834542706db9ca',1,'VT::V0::VKStruct_Base']]],
  ['vt_5fbackend_2ehpp',['VT_Backend.hpp',['../VT__Backend_8hpp.html',1,'']]],
  ['vt_5fcommand_2ehpp',['VT_Command.hpp',['../VT__Command_8hpp.html',1,'']]],
  ['vt_5fconstants_2ehpp',['VT_Constants.hpp',['../VT__Constants_8hpp.html',1,'']]],
  ['vt_5fcpp_5fstl_2ehpp',['VT_CPP_STL.hpp',['../VT__CPP__STL_8hpp.html',1,'']]],
  ['vt_5fdebug_2ehpp',['VT_Debug.hpp',['../VT__Debug_8hpp.html',1,'']]],
  ['vt_5fenums_2ehpp',['VT_Enums.hpp',['../VT__Enums_8hpp.html',1,'']]],
  ['vt_5fgpu_2ehpp',['VT_GPU.hpp',['../VT__GPU_8hpp.html',1,'']]],
  ['vt_5fgpu_5fcomms_2ehpp',['VT_GPU_Comms.hpp',['../VT__GPU__Comms_8hpp.html',1,'']]],
  ['vt_5finitialization_2ehpp',['VT_Initialization.hpp',['../VT__Initialization_8hpp.html',1,'']]],
  ['vt_5finlinespecifier',['VT_InlineSpecifier',['../group__Vault__0.html#gae26a063787d7d419d778ceb6e8a9c01f',1,'VT_Backend.hpp']]],
  ['vt_5flogicaldevice_2ehpp',['VT_LogicalDevice.hpp',['../VT__LogicalDevice_8hpp.html',1,'']]],
  ['vt_5fmemory_2ehpp',['VT_Memory.hpp',['../VT__Memory_8hpp.html',1,'']]],
  ['vt_5fmemory_5fbackend_2ehpp',['VT_Memory_Backend.hpp',['../VT__Memory__Backend_8hpp.html',1,'']]],
  ['vt_5fphysicaldevice_2ehpp',['VT_PhysicalDevice.hpp',['../VT__PhysicalDevice_8hpp.html',1,'']]],
  ['vt_5fpipelines_2ehpp',['VT_Pipelines.hpp',['../VT__Pipelines_8hpp.html',1,'']]],
  ['vt_5fplatform_2ehpp',['VT_Platform.hpp',['../VT__Platform_8hpp.html',1,'']]],
  ['vt_5frenderpass_2ehpp',['VT_RenderPass.hpp',['../VT__RenderPass_8hpp.html',1,'']]],
  ['vt_5fresource_2ehpp',['VT_Resource.hpp',['../VT__Resource_8hpp.html',1,'']]],
  ['vt_5fsampler_2ehpp',['VT_Sampler.hpp',['../VT__Sampler_8hpp.html',1,'']]],
  ['vt_5fshaders_2ehpp',['VT_Shaders.hpp',['../VT__Shaders_8hpp.html',1,'']]],
  ['vt_5fsurface_2ehpp',['VT_Surface.hpp',['../VT__Surface_8hpp.html',1,'']]],
  ['vt_5fswapchain_2ehpp',['VT_SwapChain.hpp',['../VT__SwapChain_8hpp.html',1,'']]],
  ['vt_5fsyncandcachecontrol_2ehpp',['VT_SyncAndCacheControl.hpp',['../VT__SyncAndCacheControl_8hpp.html',1,'']]],
  ['vt_5ftypes_2ehpp',['VT_Types.hpp',['../VT__Types_8hpp.html',1,'']]],
  ['vt_5fvaults_2ehpp',['VT_Vaults.hpp',['../VT__Vaults_8hpp.html',1,'']]],
  ['vt_5fvkstruct_5fbase',['VT_VKStruct_Base',['../group__Vault__0.html#ga710126d2f4fb6fac43ce6160adb78a5c',1,'VT_Backend.hpp']]],
  ['vt_5fvulkan_5fincludeguard',['VT_VULKAN_INCLUDEGUARD',['../VT__Platform_8hpp.html#aaf4dcde735865d08a24f56033627897f',1,'VT_Platform.hpp']]],
  ['vulkan11',['Vulkan11',['../structVT_1_1V1_1_1PhysicalDevice_1_1Properties_1_1Vulkan11.html',1,'VT::V1::PhysicalDevice::Properties']]],
  ['vulkan11',['Vulkan11',['../structVT_1_1V2_1_1PhysicalDevice_1_1Properties_1_1Vulkan11.html',1,'VT::V2::PhysicalDevice::Properties']]],
  ['vulkan12',['Vulkan12',['../structVT_1_1V1_1_1PhysicalDevice_1_1Properties_1_1Vulkan12.html',1,'VT::V1::PhysicalDevice::Properties']]],
  ['vulkan12',['Vulkan12',['../structVT_1_1V2_1_1PhysicalDevice_1_1Properties_1_1Vulkan12.html',1,'VT::V2::PhysicalDevice::Properties']]],
  ['vulkanapi_5fspecification',['VulkanAPI_Specification',['../group__VulkanAPI__Specification.html',1,'']]]
];
