/*!
@file VT_Vaults.hpp

@brief Vaulted Thermals: Vault Definitions

@details

Vaults (Designator):
MagmaChamber
V0
V1
V2
V3
V4


Important: Higher numbered vaults may require a lower level vault to be opened. 
If the vault is not open, it will define the open definition itself implicitly.

Opening the MagmaChamber vault is unique in that it affects all other vaults.
When opened, the definition will change the loader interfaced with for all the implementation
in the other vaults to the loader generated by the MagmaChamber vault.
Define macro: VT_Vault_MagmaChamber_Open if you want this. [Note: Currently not implemented
*/



#pragma once



#ifndef VT_Option__Use_Long_Namespace
/**
@defgroup VaultedThermals

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper

@details For long namespace: #define VT_Option__Use_Long_Namespace
*/
namespace VT
#else
/**
@defgroup VaultedThermals
@{

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper)

@details VT_Option__Use_Long_Namespace in use.
*/
namespace VaultedThermals
#endif
{
	/** 
	@defgroup Corridors
	@{
	
	@brief Contains shared definitions between the vaults.

	@details Namespace: Corridors

	@ingroup VaultedThermals
	*/
	namespace Corridors {}
	/** @} */

	/** 
	@defgroup Vault_MagmaChamber
	@{

	@brief Meta-Loading Setup.

	@details When the heat at the control gate isn't enough.

	Namespace: Vault_MagmaChamber

	@ingroup VaultedThermals

	@todo #TODO Look into possibly implementing with the Volk library.
	*/
	namespace Vault_MagmaChamber {}
	/** @} */

	/** 
	@defgroup Vault_0
	@{

	@brief Backend vault for VaultedThermals

	@details For now only abstracts away OS Platform details and basic meta-structure definitions.

	Namespace: V0

	@ingroup VaultedThermals
	*/
	namespace V0 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_1
	@{

	@brief 1:1 Wrapping of Vulkan API

	@details Namespace: V1

	@ingroup VaultedThermals
	*/
	namespace V1 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_2
	@{

	@brief Repetitive functionality wrapping.

	@details Namespace: V2

	@ingroup VaultedThermals
	*/
	namespace V2 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_3
	@{

	@brief Object-Oriented wrapping

	@details Namespace: V3

	@ingroup VaultedThermals
	*/
	namespace V3 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_4
	@{

	@brief Object-Oriented bootstrapped backend

	@details Namespace: V4

	@ingroup VaultedThermals
	*/
	namespace V4 { using namespace Corridors; }
	/** @} */
}



/**
@defgroup API_Specification

@brief The library organized based on the chapters of the Vulkan official specification.

@details
<a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/index.html">Specification</a> 
*/

/**
@defgroup APISpec_Introduction
@ingroup API_Specification

@brief Chapter 1: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap2.html">Specification</a> 
*/

/**
@defgroup APISpec_Fundamentals
@ingroup API_Specification

@brief Chapter 2: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap3.html">Specification</a> 
*/

/**
@defgroup APISpec_Initialization
@ingroup API_Specification

@brief Chapter 3: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap4.html">Specification</a> 
*/

/**
@defgroup APISpec_Devices_and_Queues
@ingroup API_Specification

@brief Chapter 4: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap5.html">Specification</a> 
*/

/**
@defgroup APISpec_Command_Buffers
@ingroup API_Specification

@brief Chapter 5: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap6.html">Specification</a> 
*/

/**
@defgroup APISpec_Synchronization_and_Cache_Control
@ingroup API_Specification

@brief Chapter 6: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap7.html">Specification</a> 
*/

/**
@defgroup APISpec_Render_Pass
@ingroup API_Specification

@brief Chapter 7: <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap8.html">Specification</a> 
*/

/**
@defgroup APISpec_Shaders
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap9.html">Specification</a> 
*/

/**
@defgroup APISpec_Pipelines
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap10.html">Specification</a>
*/

/**
@defgroup APISpec_Memory_Allocation
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap11.html">Specification</a> 
*/

/**
@defgroup APISpec_Resource_Creation
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap12.html">Specification</a> 
*/

/**
@defgroup APISpec_Samplers
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap13.html">Specification</a> 
*/

/**
@defgroup APISpec_Resource_Descriptors
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap14.html">Specification</a> 
*/

/**
@defgroup APISpec_Shader_Interfaces
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap15.html">Specification</a> 
*/

/**
@defgroup APISpec_Image_Operations
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap16.html">Specification</a> 
*/

/**
@defgroup APISpec_Fragment_Density_Map_Operations
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap17.html">Specification</a> 
*/

/**
@defgroup APISpec_Queries
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap18.html">Specification</a> 
*/

/**
@defgroup APISpec_Clear_Commands
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap19.html">Specification</a> 
*/

/**
@defgroup APISpec_Copy_Commands
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap20.html">Specification</a> 
*/

/**
@defgroup APISpec_Drawing_Commands
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap21.html">Specification</a>
*/

/**
@defgroup APISpec_Fixed-Function_Vertex_Processing
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap22.html">Specification</a> 
*/

/**
@defgroup APISpec_Tessellation
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap23.html">Specification</a> 
*/

/**
@defgroup APISpec_Geometry_Shading
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap24.html">Specification</a> 
*/

/**
@defgroup APISpec_Mesh_Shading
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap25.html">Specification</a> 
*/

/**
@defgroup APISpec_Fixed-Function_Vertex_Post-Processing
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap26.html">Specification</a> 
*/

/**
@defgroup APISpec_Rasterization
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap27.html">Specification</a> 
*/

/**
@defgroup APISpec_Fragment_Operations
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap28.html">Specification</a> 
*/

/**
@defgroup APISpec_The_Framebuffer
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap29.html">Specification</a> 
*/

/**
@defgroup APISpec_Dispatching_Commands
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap30.html">Specification</a> 
*/

/**
@defgroup APISpec_Device-Generated_Commands
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap31.html">Specification</a> 
*/

/**
@defgroup APISpec_Sparse_Resources
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/lastest/windows/chunked_spec/chap32.html">Specification</a> 
*/

/**
@defgroup APISpec_Window_System_Integration_WSI
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap33.html">Specification</a> 
*/

/**
@defgroup APISpec_Deferred_Host_Operations
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap34.html">Specification</a> 
*/

/**
@defgroup APISpec_Private_Data
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap35.html">Specification</a> 
*/

/**
@defgroup APISpec_Ray_Traversal
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap36.html">Specification</a> 
*/

/**
@defgroup APISpec_Ray_Tracing
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap37.html">Specification</a> 
*/

/**
@defgroup APISpec_Extending_Vulkan
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap38.html">Specification</a> 
*/

/**
@defgroup APISpec_Features
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap39.html">Specification</a> 
*/

/**
@defgroup APISpec_Limits
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap40.html">Specification</a> 
*/

/**
@defgroup APISpec_Formats
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap41.html">Specification</a> 
*/

/**
@defgroup APISpec_Additional_Capabilities
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap42.html">Specification</a> 
*/

/**
@defgroup APISpec_Debugging
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap43.html">Specification</a> 
*/

/**
@defgroup APISpec__Appendix-A__Vulkan-Environment_for_SPIR-V
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap44.html">Specification</a>  
*/

/**
@defgroup APISpec__Appendix-B__Memory_Model
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap45.html">Specification</a> 
*/

/** 
@defgroup APISpec__Appendix-C__Compressed_Image_Formats
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap46.html">Specification</a> 
*/

/**
@defgroup APISpec__Appendix-D__Core_Revisions_-Informative-
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap47.html">Specification</a> 
*/

/** 
@defgroup APISpec__Appendix-E__Layers_and_Extensions_-Informative-
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap48.html">Specification</a> 
*/

/**
@defgroup APISpec__Appendix-F__API_Boilerplate
@ingroup API_Specification

@brief <a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/chunked_spec/chap49.html">Specification</a> 
*/
