/*!
@file VT_Vaults.hpp

@brief Vaulted Thermals: Vault Definitions

@details

Vaults (Designator):
MagmaChamber
V0
V1
V2
V3
V4


Important: Higher numbered vaults may require a lower level vault to be opened. 
If the vault is not open, it will define the open definition itself implicitly.

Opening the MagmaChamber vault is unique in that it affects all other vaults.
When opened, the definition will change the loader interfaced with for all the implementation
in the other vaults to the loader generated by the MagmaChamber vault.
Define macro: VT_Vault_MagmaChamber_Open if you want this. [Note: Currently not implemented
*/



#pragma once



#include "VT_APISpecGroups.hpp"



#ifndef VT_Option__Use_Long_Namespace
/**
@defgroup VaultedThermals

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper

@details For long namespace: #define VT_Option__Use_Long_Namespace
*/
namespace VT
#else
/**
@defgroup VaultedThermals
@{

@brief Main library namespace for Vaulted Thermals (Vulkan Wrapper)

@details VT_Option__Use_Long_Namespace in use.
*/
namespace VaultedThermals
#endif
{
	/** 
	@defgroup Corridors
	@{
	
	@brief Contains shared definitions between the vaults.

	@details Namespace: Corridors

	@ingroup VaultedThermals
	*/
	namespace Corridors {}
	/** @} */

	/** 
	@defgroup Vault_MagmaChamber
	@{

	@brief Meta-Loading Setup.

	@details When the heat at the control gate isn't enough.

	Namespace: Vault_MagmaChamber

	@ingroup VaultedThermals

	@todo #TODO Look into possibly implementing with the Volk library.
	*/
	namespace Vault_MagmaChamber {}
	/** @} */

	/** 
	@defgroup Vault_0
	@{

	@brief Backend vault for VaultedThermals

	@details For now only abstracts away OS Platform details and basic meta-structure definitions.

	@ingroup VaultedThermals
	*/
	namespace V0 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_1
	@{

	@brief 1:1 Wrapping of Vulkan API

	@details 

	@ingroup VaultedThermals
	*/
	namespace V1 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_2
	@{

	@brief Repetitive functionality wrapping.

	@details 

	@ingroup VaultedThermals
	*/
	namespace V2 { using namespace Corridors; }
	/** @} */

	/** 
	@defgroup Vault_3
	@{

	@brief Object-Oriented wrapping

	@details 

	@ingroup VaultedThermals
	*/
	namespace V3 { using namespace Corridors; }
	/** @} */

#ifdef VT_Open_Vault_4

	/** 
	@defgroup Vault_4
	@{

	@brief Object-Oriented bootstrapped backend

	@details 

	@ingroup VaultedThermals
	*/
	namespace V4 
	{ 
		using namespace Corridors;
	}

#endif

	/** @} */
}
